### ISSUE TITLE
Facebook embeds broken

### ISSUE THREAD

**Issue by md5** [socialimpactlab/socialimpactlab.github.io#1]
It like commit 56a1d5c42180f9764d47a673b6b33347bb8171fc broke Facebook embeds for your site. The missing space in `<meta property="og:type"content="website" />` causes Facebook's Open Graph parser to ignore all the other meta `og:*` tags on the page. :disappointed:

Here's the Facebook Debugger link for the blog post I noticed the problem on: https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fsimlab.org%2Fblog%2F2015%2F05%2F21%2Ffirst-resort%2F

Great work on that project, by the way! I learned about it via Open Referral.

**Comment by keithporcaro** [comment]
Hi Mike

Thanks for the catch! We'll have a look.

k

**Comment by md5** [comment]
This appears to have been fixed in https://github.com/socialimpactlab/socialimpactlab.github.io/commit/122cab7345c9120b34d69c70fd35adb0f29ccb24
